#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap latam
feh --bg-fill /home/ricardo/Desktop/wallpaper.jpg &
/home/ricardo/.config/polybar/launch.sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
